### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by yoavram** [sbi-dev/pyknos#24]
The readme says the examples are in an examples folder, but I don't see such a folder :)

**Comment by janfb** [comment]
It seems this statement in the README is not accurate anymore. The `pyknos` package is mainly a wrapper for different density estimation methods used the [sbi](https://github.com/mackelab/sbi) package. 
We have several tutorials and examples available there as well.

**Comment by yoavram** [comment]
Thanks. Can you provide a reference to those examples/tutorials?

**Comment by janfb** [comment]
https://github.com/mackelab/sbi/tree/main/tutorials
